### ISSUE TITLE
Changing value on the $scope not updating the editor?

### ISSUE THREAD

**Issue by Madd0g** [angular-ui/ui-ace#64]
Hi,

I was a bit surprised to find out that when I update the $scope variable, the editor does not update.
Do I need to call some update method? Does that mean I need to save the editor from the onLoad event? Or is there something I can inject into my controller?

I'm wondering why this is not built-in.

Thanks

**Comment by douglasduteil** [comment]
Can you confirm that it's fixed with #87 #77 ?

**Comment by judytrinh** [comment]
I still have this issue, using the latest version 0.2.3. I have a uib-tabset, and in tab no.1 I have a ui-ace div where I type text to update the ng-model. In tab no.2, I have a readonly ui-ace div that should reflect what I have changed because it has the same ng-model as the first. When I switch to tab no.2, the ui-ace does not update until I click into it or trigger other events like a tooltip hover over outside of the tabset, etc. If I place the readonly ui-ace input in tab no.1, however, it updates just fine. If I place the ng-model variable in between {{}} in tab no.2, it updates just fine. So, I think it is a similar issue discussed in this thread.

I am aware of this issue with tabsets: http://stackoverflow.com/questions/27513462/angularjs-ngmodel-doesnt-work-inside-a-ui-bootstrap-tabset
I am not using a primitive on the scope for my ng-model -- I am using an object attached to my controller referencing it with the help of controllerAs. So I'm not sure what could be the issue. Any ideas?

**Comment by judytrinh** [comment]
An fyi, I managed to temporarily fix the issue with a hack where I call a $timeout( function() { $rootScope.$broadcast('update-ace-editor-hack'); } ) upon clicking tab no.2 so that the editor receives an event to trigger its refresh.

Edit: actually, it seems that all that isn't even necessary - just putting ng-click directive on the uib-tab element triggers the refresh itself.

**Comment by janzhongi** [comment]
before find a better solution,I fixed in this way.
run aceEditor.setValue() will update the editor content.
first you need to get the editor in ui-ace.onload function
$scope.editor;
$scope.aceLoaded = function (_editor) {
...
$scope.editor = _editor;
....
}

and use $scope.aceEditor.setValue(newValue) to trigger the refresh;

**Comment by dduft** [comment]
This is not solved! Thank you judytrinh for the hack! But for me the broadcast was necessary as well.

**Comment by ym13349140** [comment]
I met with this problem too,and I used `editor.renderer.updateFull();` worked.
